package lox.scanner;

public enum TokenType{
    // KEYWORDS
    CLASS, FUN, VAR, FOR, WHILE, PRINT, RETURN, IF, ELSE, SUPER, THIS,

    // ARITHMETIC OPERATORS
    ADD, SUBTRACT, MULTIPLY, DIVIDE, LT, GT, LEQ, GEQ, EQ, NEQ, NOT, 

    // SYMBOLS
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, SEMICOLON, DOT, COMMA, ASSIGNMENT,

    // BOOLEAN OPERATORS AND VALUES
    OR, AND, TRUE, FALSE, NIL,

    // STRING AND NUMBER LITERALS
    STRING, NUMBER, IDENTIFIER,

    // EOF
    EOF;
}